FROM centos

RUN yum install -y curl && \
    yum install -y syslinux && \
    yum -y clean all --enablerepo='*'


# CMD curl www.google.com

# CMD gethostip www.google.com

CMD curl 192.168.0.168:8880

# CMD ping 192.168.0.168